// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Service.Models;

namespace ProjectMono.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200403082706_t1")]
    partial class t1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Service.VehicleMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VehicleMake");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "bmw",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "toyota",
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("Project.Service.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv");

                    b.Property<int?>("MakeIdId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MakeIdId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Project.Service.VehicleModel", b =>
                {
                    b.HasOne("Project.Service.VehicleMake", "MakeId")
                        .WithMany("vehicleModels")
                        .HasForeignKey("MakeIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
