// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Service.Models;

namespace ProjectMono.Migrations
{
    [DbContext(typeof(Project.Service.Models.DbContext))]
    [Migration("20200404163945_initDb1")]
    partial class initDb1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Service.VehicleMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VehicleMake");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "Bmw",
                            Name = "BMW Group"
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "benz",
                            Name = "Mercedes-Benz company"
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "toyota",
                            Name = "Toyota motor"
                        },
                        new
                        {
                            Id = 4,
                            Abrv = "mazda",
                            Name = "Mazda motor"
                        },
                        new
                        {
                            Id = 5,
                            Abrv = "lexus",
                            Name = "Lexus - Rekusasu"
                        });
                });

            modelBuilder.Entity("Project.Service.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv");

                    b.Property<int>("MakeId");

                    b.Property<string>("Name");

                    b.Property<int?>("VehicleMakeId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleMakeId");

                    b.ToTable("VehicleModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "CX-5",
                            MakeId = 4,
                            Name = "Mazda CX-5 2020"
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "RX-8",
                            MakeId = 4,
                            Name = "Mazda RX-8"
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "GX",
                            MakeId = 5,
                            Name = "Lexus GX"
                        },
                        new
                        {
                            Id = 4,
                            Abrv = "Supra",
                            MakeId = 3,
                            Name = "GR Supra"
                        },
                        new
                        {
                            Id = 5,
                            Abrv = "SL",
                            MakeId = 2,
                            Name = "Mercedes-Benz SL-klasa"
                        },
                        new
                        {
                            Id = 6,
                            Abrv = "BMW 4C",
                            MakeId = 1,
                            Name = "BMW serija 4 Coupe"
                        });
                });

            modelBuilder.Entity("Project.Service.VehicleModel", b =>
                {
                    b.HasOne("Project.Service.VehicleMake")
                        .WithMany("vehicleModels")
                        .HasForeignKey("VehicleMakeId");
                });
#pragma warning restore 612, 618
        }
    }
}
